### ISSUE TITLE
Add support for CC-BY-3.0

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/bom-bar#19]
We currently do not support `CC-BY-3.0`.

<img width="1301" alt="Screenshot 2021-03-22 at 10 01 21" src="https://user-images.githubusercontent.com/10019/111965181-c021e700-8af5-11eb-99b2-4bd2f4b18276.png">

**Comment by timovandeput** [comment]
Added in commit https://github.com/philips-software/bom-bar/commit/175e83e89bc78b57a225e4facdeb604aaae55efb
