### ISSUE TITLE
Add export SPDX file

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/bom-bar#48]

**Comment by timovandeput** [comment]
BOM-Bar is intended for violations checking, and it is not an asset management tool. I believe that SPDX files should be stored with the project before uploading, and BOM-Bar should only be used as a trigger to act on non-compliancies. Downloading (potentially outdated) SPDX files could in this context even be considered a dangerous idea.

Therefore I don't think this is a good idea to store the SPDX file in BOM-Bar and allow downloading.

Note that BOM-Bar already exposes the timestamp of the SPDX file, so it is possible to retrace which SPDX file was last uploaded.

**Comment by JeroenKnoops** [comment]
true.
